version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
      POSTGRES_DB: Library

  app:
    build: .
    container_name: library_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Library
      SPRING_DATASOURCE_USERNAME: ***
      SPRING_DATASOURCE_PASSWORD: ***

volumes:
  pgdata: